name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17'  # Ensure compatibility, you might switch to '18.x' or '16.x'

      - name: Install Dependencies
        run: npm install

      - name: Build the application
        run: npx ng build --configuration production

      - name: Delete Build Folder
        run: sudo rm -rf /var/www/html/angular-app5

      - name: Create Build Folder
        run: sudo mkdir -p /var/www/html/angular-app5

      - name: Ensure directory permissions
        run: sudo chown -R $(whoami):$(whoami) /var/www/html/angular-app5

      - name: Copy build files to deployment directory
        run: sudo cp -r dist/project-mdb/* /var/www/html/angular-app5

      - name: Deploy (if necessary)
        run: |
          echo "Deploying the application..."
          # Add your deployment commands here, e.g., restart a service or upload to a server
